# backend/ingestion/vector_store.py
# ─────────────────────────────────────────────────────────
# This file handles two things:
#
# 1. EMBED  → Convert each text chunk into numbers (vectors)
#             that represent its meaning mathematically.
#             We use sentence-transformers which runs fully
#             locally — no API key, no internet, no limits.
#
# 2. STORE  → Save those vectors into ChromaDB locally
#             along with the original text and metadata
#             (department, filename) for filtering later.
#
# Model: all-MiniLM-L6-v2
#   - Size: ~90MB (downloads once automatically)
#   - Speed: very fast on CPU
#   - Quality: excellent for semantic search
#   - Works on: laptop, free hosting servers, everywhere
# ─────────────────────────────────────────────────────────

import chromadb
from chromadb.utils import embedding_functions
from core.config import settings


class VectorStoreManager:
    """
    Manages our ChromaDB vector store.

    Uses sentence-transformers locally for embeddings —
    no API key needed, no rate limits, works offline,
    and works perfectly on free hosting servers.
    """

    def __init__(self):
        print("   🔄 Loading embedding model...")
        print("   (First run downloads ~90MB — one time only)")

        # SentenceTransformerEmbeddingFunction is built into ChromaDB
        # It downloads the model automatically on first use
        # After that it loads from local cache instantly
        self.embedding_fn = (
            embedding_functions.SentenceTransformerEmbeddingFunction(
                model_name="all-MiniLM-L6-v2"
            )
        )

        print("   ✅ Embedding model ready!")

        # Connect to ChromaDB
        # PersistentClient saves everything to disk
        # Data survives restarts — you don't re-embed every time
        self.client = chromadb.PersistentClient(
            path=settings.chroma_db_path
        )

        # Get or create our collection
        # A collection is like a table in a regular database
        # We use cosine similarity — best for comparing text meaning
        self.collection = self.client.get_or_create_collection(
            name=settings.collection_name,
            embedding_function=self.embedding_fn,
            metadata={"hnsw:space": "cosine"}
        )

        print(f"   ✅ ChromaDB connected → '{settings.collection_name}'")
        print(f"   📊 Current chunks in store: {self.collection.count()}")


    def store_chunks(self, chunks: list[dict]) -> None:
        """
        Embeds and stores all chunks in ChromaDB.

        For each chunk we store:
        - ids        → unique ID per chunk (prevents duplicates)
        - documents  → the actual text (returned in answers)
        - embeddings → vectors (auto-generated by sentence-transformers)
        - metadatas  → department + filename (used for role filtering)
        """

        if not chunks:
            print("⚠️  No chunks to store.")
            return

        print(f"\n💾 Storing {len(chunks)} chunks in ChromaDB...")
        print("   Running embeddings locally — no API calls needed")
        print("─" * 50)

        # Batch size of 100 — local embeddings are fast
        # so we can process more at once
        batch_size = 100

        for i in range(0, len(chunks), batch_size):
            batch         = chunks[i:i + batch_size]
            batch_num     = (i // batch_size) + 1
            total_batches = (len(chunks) + batch_size - 1) // batch_size

            print(f"   📦 Batch {batch_num}/{total_batches} "
                  f"({len(batch)} chunks)...", end=" ", flush=True)

            ids       = [c["chunk_id"] for c in batch]
            documents = [c["content"]  for c in batch]
            metadatas = [
                {
                    "department":  c["department"],
                    "filename":    c["filename"],
                    "filepath":    c["filepath"],
                    "chunk_index": str(c["chunk_index"])
                }
                for c in batch
            ]

            # ChromaDB automatically calls our embedding_fn
            # to convert documents → vectors before storing
            # upsert = insert if new, update if already exists
            # Safe to re-run without creating duplicates
            self.collection.upsert(
                ids=ids,
                documents=documents,
                metadatas=metadatas
            )

            print("✅")

        print(f"\n✅ All chunks stored successfully!")
        print(f"   Total in vector store: {self.collection.count()}")


    def get_stats(self) -> dict:
        """Returns basic stats about the vector store."""
        return {
            "total_chunks":    self.collection.count(),
            "collection_name": settings.collection_name,
            "db_path":         settings.chroma_db_path
        }